# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19Gb7i5u4WcIdmYbvWvJj-g5y4HlAhcqy
"""

import matplotlib.pyplot as plt
x=[]
y=[]
symbol=[]
i=0

file_path = "./hello/text.txt"

with open(file_path) as file:

    for line in file:
        cleaned_line = line.strip()
        if i==0:
          x.append(cleaned_line)
        elif i==1:
          symbol.append(cleaned_line)
        elif i==2:
          y.append(cleaned_line)
          i=-1
        i+=1
x=x[1:]
y=y[1:]
symbol=symbol[1:]

for i in range(len(x)):
  x[i]=int(x[i])
  y[i]=int(y[i])
print(x)
print(y)
print(symbol)

# Find Max of X-axis and Y-axis
x_max=max(x)
y_max=max(y)


plt.figure(figsize=(x_max, y_max))

# Plot all points
plt.scatter(x, y, s=100, color='skyblue', edgecolors='black')

# Add text labels
for xi, yi, sym in zip(x, y, symbol):
    plt.text(xi, yi, sym, fontsize=8, ha='center', va='center', color='black')

# Formatting
plt.grid(True, linestyle='--', linewidth=0.5)
plt.xlabel("X")
plt.ylabel("Y")
plt.title("Scatter Plot of 350 Symbols")
plt.tight_layout()
plt.show()